### ISSUE TITLE
Support PHP, JS and Flash targets

### ISSUE THREAD

**Issue by mpcref** [rjsmith/hxzmq#2]
Cool library!
You might also be interested in offering support for other haXe targets so that the same sourcecode can also be compiled to PHP, JS or Flash based on these existing zeromq bindings:
PHP: http://www.zeromq.org/bindings:php
JS: http://www.zeromq.org/bindings:javascript
Flash: http://www.zeromq.org/bindings:actionscript-zmqsocket

**Comment by rjsmith** [comment]
Hi - thanks very much for the feedback.
re: other bindings - I have plans for adding php at least in near future (it's not a target I have used myself in haXe, so I need a bit of familiarisation time).  Not sure about the JS and Flash bindings, as they are only partial wire-level transport implementations, vs all the diff socket types provided by the libzmq library.  Will have to see how they could be incorporated into the hxzmq API.  If you have any suggestions, please let me know!

**Comment by rjsmith** [comment]
I have pushed an update that wraps the php-zmq binding within the hxzmq haXe code, when targetting PHP.  

I think that the JS and Flash ports would be better off separated in a different project that is focused on the zeroMQ wire-level protocol; the client-facing API would be quite different to that of hxzmq (no support for different ZMQ socket types, message queuing behaviour and socket options etc).  I suspect that adopting another approach using something like Mongrel2 as the interface between the web world and the back-end neko/cpp/php server environment would work better perhaps?
